
import { 
  Terminal, 
  FolderOpen, 
  Globe, 
  Settings, 
  Cpu, 
  Image as ImageIcon, 
  Code2, 
  LayoutGrid,
  Wifi,
  Volume2,
  Battery,
  Bluetooth,
  Monitor,
  HardDrive,
  Download,
  FileText,
  Music,
  Video,
  Folder,
  Search,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  Plus,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  ChevronDown,
  Home,
  Trash2,
  Edit,
  Copy,
  ExternalLink,
  Check,
  X as XIcon,
  MoreHorizontal,
  List,
  Grid,
  Eye,
  Scissors,
  Clipboard,
  RefreshCw,
  Maximize,
  Minimize,
  Layout,
  MousePointer2,
  AppWindow,
  Info,
  Calculator,
  ShoppingBag,
  Activity,
  Lock,
  Bell,
  Moon,
  Sun,
  Shield,
  Zap,
  RotateCw,
  RotateCcw,
  Minus,
  ZoomIn,
  ZoomOut,
  Calendar,
  Clock,
  CreditCard,
  WifiOff,
  BluetoothOff,
  Mic,
  Camera,
  User,
  History,
  Save,
  Chrome,
  Command,
  Server,
  MoreVertical,
  Star,
  GitBranch,
  XCircle,
  AlertTriangle,
  Map,
  Play,
  Palette,
  Film,
  Clapperboard,
  CloudSun,
  Newspaper,
  Construction,
  StickyNote,
  Timer,
  StopCircle,
  Hourglass,
  Mail,
  Inbox,
  Send,
  Archive,
  CheckSquare,
  Tag,
  Phone,
  Users,
  MapPin,
  CloudRain,
  CloudLightning,
  CloudSnow,
  Wind,
  Droplets,
  Bot,
  Table,
  Bomb,
  Flag,
  File,
  Smile,
  Gamepad2,
  Sliders,
  LayoutDashboard,
  CircleDot,
  GalleryHorizontal,
  MonitorUp,
  Hash,
  Circle,
  Brush,
  Pin,
  BellOff
} from 'lucide-react';
import { FileSystemNode } from './types';

export const WALLPAPER_URLS = [
  "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=2072&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=2070&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1477346611705-65d1883cee1e?q=80&w=2070&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=2064&auto=format&fit=crop"
];

export const TRIAL_DURATION_MS = 10 * 60 * 1000; // 10 Minutes

export const ICONS = {
  Terminal,
  FolderOpen,
  Globe,
  Settings,
  Cpu,
  ImageIcon,
  Code2,
  LayoutGrid,
  Wifi,
  Volume2,
  Battery,
  Bluetooth,
  Monitor,
  HardDrive,
  Download,
  FileText,
  Music,
  Video,
  Folder,
  Search,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  Plus,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  ChevronDown,
  Home,
  Trash2,
  Edit,
  Copy,
  ExternalLink,
  Check,
  XIcon,
  MoreHorizontal,
  List,
  Grid,
  Eye,
  Scissors,
  Clipboard,
  RefreshCw,
  Maximize,
  Minimize,
  Layout,
  MousePointer2,
  AppWindow,
  Info,
  Calculator,
  ShoppingBag,
  Activity,
  Lock,
  Bell,
  Moon,
  Sun,
  Shield,
  Zap,
  RotateCw,
  RotateCcw,
  Minus,
  ZoomIn,
  ZoomOut,
  Calendar,
  Clock,
  CreditCard,
  WifiOff,
  BluetoothOff,
  Mic,
  Camera,
  User,
  History,
  Save,
  Chrome,
  Command,
  Server,
  MoreVertical,
  Star,
  GitBranch,
  XCircle,
  AlertTriangle,
  Map,
  Play,
  Palette,
  Film,
  Clapperboard,
  CloudSun,
  Newspaper,
  Construction,
  StickyNote,
  Timer,
  StopCircle,
  Hourglass,
  Mail,
  Inbox,
  Send,
  Archive,
  CheckSquare,
  Tag,
  Phone,
  Users,
  MapPin,
  CloudRain,
  CloudLightning,
  CloudSnow,
  Wind,
  Droplets,
  Bot,
  Table,
  Bomb,
  Flag,
  File,
  Smile,
  Gamepad2,
  Sliders,
  LayoutDashboard,
  CircleDot,
  GalleryHorizontal,
  MonitorUp,
  Hash,
  Circle,
  Brush,
  Pin,
  BellOff
};

export const INITIAL_FILES: FileSystemNode[] = [
  {
    id: 'root',
    name: 'Root',
    type: 'folder',
    dateModified: new Date('2024-10-24T10:00:00'),
    dateCreated: new Date('2024-10-24T09:00:00'),
    children: [
      {
        id: '1',
        name: 'Documents',
        type: 'folder',
        dateModified: new Date('2024-10-24T10:05:00'),
        dateCreated: new Date('2024-10-24T10:05:00'),
        children: [
          { id: '11', name: 'Project_Alpha.txt', type: 'file', content: 'CONFIDENTIAL\n\nProject Alpha is a next-gen hybrid OS initiative.\nTarget release: Q4 2025.\nStatus: In Development.', size: '2 KB', dateModified: new Date('2024-10-23T14:20:00'), dateCreated: new Date('2024-10-23T14:20:00') },
          { id: '12', name: 'Notes.md', type: 'file', content: '# Daily Notes\n\n- [x] Buy milk\n- [ ] Fix bugs in kernel\n- [ ] Review PRs', size: '1 KB', dateModified: new Date('2024-10-24T09:15:00'), dateCreated: new Date('2024-10-24T09:15:00') },
          { id: '13', name: 'Budget_2024.csv', type: 'file', content: 'Item,Cost,Category\nServer,500,Infra\nCoffee,1000,Fuel\nLicenses,200,Software', size: '4 KB', dateModified: new Date('2024-10-20T11:00:00'), dateCreated: new Date('2024-10-20T11:00:00') }
        ]
      },
      {
        id: '2',
        name: 'Downloads',
        type: 'folder',
        dateModified: new Date('2024-10-24T12:30:00'),
        dateCreated: new Date('2024-10-24T12:30:00'),
        children: [
           { id: '21', name: 'installer_v2.dmg', type: 'file', content: '[Binary Data Corrupted]', size: '150 MB', dateModified: new Date('2024-10-24T12:25:00'), dateCreated: new Date('2024-10-24T12:25:00') },
           { id: '22', name: 'manual.pdf', type: 'file', content: 'Windora OS User Manual\n\nChapter 1: Getting Started...', size: '2.5 MB', dateModified: new Date('2024-10-25T10:00:00'), dateCreated: new Date('2024-10-25T10:00:00') }
        ]
      },
      {
        id: '3',
        name: 'Desktop',
        type: 'folder',
        dateModified: new Date('2024-10-24T08:00:00'),
        dateCreated: new Date('2024-10-24T08:00:00'),
        children: [
           { id: '31', name: 'welcome.py', type: 'file', content: 'def welcome():\n    print("Welcome to Windora OS!")\n    print("Enjoy the hybrid experience.")\n\nif __name__ == "__main__":\n    welcome()', size: '1 KB', dateModified: new Date('2024-10-24T08:01:00'), dateCreated: new Date('2024-10-24T08:01:00') },
           { id: '32', name: 'Mountain_View.png', type: 'file', content: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=1000&auto=format&fit=crop', size: '2.4 MB', dateModified: new Date('2024-10-22T16:45:00'), dateCreated: new Date('2024-10-22T16:45:00') }
        ]
      },
      {
        id: '4',
        name: 'Pictures',
        type: 'folder',
        dateModified: new Date('2024-10-21T09:00:00'),
        dateCreated: new Date('2024-10-21T09:00:00'),
        children: [
          { id: '41', name: 'Vacation.jpg', type: 'file', content: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1000&auto=format&fit=crop', size: '3.1 MB', dateModified: new Date('2024-09-15T10:30:00'), dateCreated: new Date('2024-09-15T10:30:00') },
          { id: '42', name: 'Design_Mockup.png', type: 'file', content: 'https://images.unsplash.com/photo-1581291518633-83b4ebd1d83e?q=80&w=1000&auto=format&fit=crop', size: '1.2 MB', dateModified: new Date('2024-10-01T14:20:00'), dateCreated: new Date('2024-10-01T14:20:00') }
        ]
      },
      {
        id: '5',
        name: 'Music',
        type: 'folder',
        dateModified: new Date('2024-10-20T18:00:00'),
        dateCreated: new Date('2024-10-20T18:00:00'),
        children: []
      },
      {
        id: '6',
        name: 'Videos',
        type: 'folder',
        dateModified: new Date('2024-10-26T14:00:00'),
        dateCreated: new Date('2024-10-26T14:00:00'),
        children: []
      },
      {
        id: 'usb',
        name: 'USB Drive (E:)',
        type: 'folder',
        dateModified: new Date('2024-10-25T09:00:00'),
        dateCreated: new Date('2024-10-25T09:00:00'),
        children: [
           { id: 'usb1', name: 'Backup.zip', type: 'file', content: '', size: '4.2 GB', dateModified: new Date('2024-10-25T09:05:00'), dateCreated: new Date('2024-10-25T09:05:00') }
        ]
      },
      {
        id: 'trash',
        name: 'Recycle Bin',
        type: 'folder',
        dateModified: new Date('2024-10-24T08:00:00'),
        dateCreated: new Date('2024-10-24T08:00:00'),
        children: []
      }
    ]
  }
];